name: using_contentful_flutter
description: "Contentful + Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  contentful_flutter: ^0.0.13
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
